## Numpy array and basics


In [1]:
import numpy as np  
import time as tm                                     

### creating array from numpy

In [2]:
arry_1d = np.array([1,2,3,4]) #1D Array
print("1D arrays", arry_1d)

arry_2d = np.array([[1,2,3,4],[5,6,7,8]]) #2D Array
print("1D arrays", arry_2d)


1D arrays [1 2 3 4]
1D arrays [[1 2 3 4]
 [5 6 7 8]]


### List vs numpy array

In [3]:


py_list = [1,2,3,4] #index wise multplication
print("python list multiplication", py_list * 2)

np_array = np.array([1,2,3,4]) #element wise multiplication
print("python list multiplication", np_array * 2)

#Checking which is fast list or numpy array:
start = tm.time()
py_list = [i*2 for i in range(10000000)]
print("\n List operation time:", tm.time() - start)

start = tm.time()
np_array = np.arange(10000000) * 2
print("\n Numpy operation time:", tm.time() - start)

python list multiplication [1, 2, 3, 4, 1, 2, 3, 4]
python list multiplication [2 4 6 8]

 List operation time: 0.9244441986083984

 Numpy operation time: 0.08460569381713867


### creating array from scratch 

In [4]:
zeros = np.zeros((4,4)) #2D Array
print("zeroes array: \n", zeros)

ones = np.ones((2,4)) #1D Array
print("ones array: \n", ones)

full = np.full((2,2), 7) #Constant Array
print("full array: \n", full)

random = np.random.random((2,4)) #random numbers 2*4 array
print("random array: \n", random)

sequence = np.arange(0, 10, 2) # sequence of numbers in an array
print("sequence array: \n", sequence)


zeroes array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.64481342 0.80721296 0.91909569 0.82833561]
 [0.53859065 0.66911357 0.80552072 0.058461  ]]
sequence array: 
 [0 2 4 6 8]


### Vector, Matrix and Tensor

In [5]:
vector = np.array([1,2,3]) #1D Array = vector
print("Vector: \n", vector)

matrix = np.array([[1,2,3],
                   [4,5,6]]) #2D Array = matrix
print("Matrix: \n", matrix)

tensor = np.array([[[1,2], [3,4]],
                   [[5,6],[7,8]]]) #3D+ Array = tensor
print("Tensor: \n", tensor)

Vector: 
 [1 2 3]
Matrix: 
 [[1 2 3]
 [4 5 6]]
Tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
